# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24.x', '1.25.x', '1.26.x' ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Test with coverage
      run: |
        go test -cover -coverprofile=coverage.txt ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: tinh-tinh/tslog